[package]
name = "proxy-enum"
version = "0.1.1"
authors = ["Moritz Bischof <moritz.bischof@aleph-alpha.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = [ "full", "visit-mut" ] }
quote = "1"
proc-macro2 = "1"